version: '3.3'
services:   
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeperC
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafkaC
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "challenge.notification.update:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  informix:
    image: appiriodevops/informix:1b3d4ef
    container_name: informixC
    ports:
      - "2021:2021"
    platform: linux/amd64
networks:
  default:
    external:
      name: lpp      
